import type { NextPage } from 'next'
import Head from 'next/head'
import GlobalState from '../store'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const store = GlobalState.useContainer();

  return (
    <div className={styles.container}>
      <Head>
        <title>Chat Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {store.visible && <div>hello</div>}
        <button onClick={()=>store.toogleVisible()}>click me!</button>
      </main>
    </div>
  )
}

export default Home
